name: Build and Publish to registry

on:
    [workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build ./frontend -t task-manager-frontend:latest
        docker build ./backend -t task-manager-backend:latest

    - name: Push to Registry
      run: |
       docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
       docker push atharva12801/task-manager-frontend:latest
       docker push atharva12801/task-manager-backend:latest
